# fly.toml app configuration file for my-rewards-script
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'my-rewards-script'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false # Changed to false to keep the machine always on
  auto_start_machines = true
  min_machines_running = 1 # Changed to 1 to ensure it stays running

# This new section tells Fly.io to attach your storage volume
[mounts]
  source="data"
  destination="/usr/src/microsoft-rewards-script/data"

# This new section sets the variables for your script
[env]
  TZ = "Asia/Kolkata"
  CRON_SCHEDULE = "0 7,15,20 * * *"
  RUN_ON_START = "true"