name: Run Microsoft Rewards Script

on:
  schedule:
    # Runs at 7:00 AM, 3:00 PM, and 8:00 PM IST (approximated in UTC)
    - cron: '30 1 * * *'
    - cron: '30 9 * * *'
    - cron: '30 14 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run the script
        run: npm run start

      - name: Commit and push session files
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add dist/browser/sessions/ # This line has been corrected
          # Check if there are changes to commit
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update session files"
            git push "https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git" HEAD:main
          fi